2023-05-01 13:20:35,550 - __init__.py:init_device[line:18] - CRITICAL: 初始化网关设备驱动 start...
2023-05-01 13:20:35,561 - device_manager.py:open[line:64] - INFO: SUCCESS : open device设备('水声通信机0')
2023-05-01 13:20:35,561 - core_scheduling.py:init_device_list_threadhandle[line:51] - INFO: 设备列表中存在1个设备, 设备0=设备('水声通信机0')
2023-05-01 13:20:35,567 - connection_workflow.py:start[line:179] - INFO: Pika version 1.3.1 connecting to ('::1', 5672, 0, 0)
2023-05-01 13:20:35,568 - io_services_utils.py:_on_writable[line:345] - INFO: Socket connected: <socket.socket fd=856, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 3147, 0, 0), raddr=('::1', 5672, 0, 0)>
2023-05-01 13:20:35,580 - connection_workflow.py:_on_transport_establishment_done[line:428] - INFO: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000021E6407F490>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000021E6407F490> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2023-05-01 13:20:35,584 - connection_workflow.py:_report_completion_and_cleanup[line:293] - INFO: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000021E6407F490> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-05-01 13:20:35,584 - connection_workflow.py:_report_completion_and_cleanup[line:725] - INFO: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000021E6407F490> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-05-01 13:20:35,584 - blocking_connection.py:_create_connection[line:453] - INFO: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000021E6407F490> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-05-01 13:20:35,585 - blocking_connection.py:__init__[line:1264] - INFO: Created channel=1
2023-05-01 13:20:35,587 - core_scheduling.py:monitor_web_task_threadhandle[line:220] - CRITICAL: SUCCESS : Create Pika server.
2023-05-01 13:20:45,682 - bsp_underwater_acoustic_comm.py:_read_bytes[line:198] - CRITICAL: 水声通信设备(端口'COM5' 状态True) 接收到一帧数据b'\xff'
2023-05-01 13:20:45,682 - bsp_underwater_acoustic_comm.py:_read_bytes[line:201] - WARNING: WARNING : 水声通信设备(端口'COM5' 状态True) read frame length is not 57
2023-05-01 13:20:45,682 - bsp_underwater_acoustic_comm.py:_read_bytes[line:203] - WARNING: WARNING : 水声通信设备(端口'COM5' 状态True) read frmae without header b'U\xaa6'
2023-05-01 13:20:45,684 - bsp_underwater_acoustic_comm.py:_read_bytes[line:209] - WARNING: WARNING : 水声通信设备(端口'COM5' 状态True) read frmae without end b'\r\n'
2023-05-01 13:20:45,684 - bsp_underwater_acoustic_comm.py:read[line:149] - ERROR: 水声通信设备(端口'COM5' 状态True)读取文件发生错误, 错误原因： 未接收到正确的CMD_FILEINFO
2023-05-01 13:20:45,685 - core_scheduling.py:deal_data_forwarding_processhandle[line:108] - ERROR: ERROR   : 线程池处理DIRECT_DEVICE_TO_FILE任务124462
2023-05-01 13:20:45,687 - core_scheduling.py:deal_data_forwarding_callback[line:156] - CRITICAL: 线程池回调 ： 执行任务{task_id}失败
2023-05-01 13:22:22,659 - bsp_underwater_acoustic_comm.py:_read_bytes[line:198] - CRITICAL: 水声通信设备(端口'COM5' 状态True) 接收到一帧数据b'\xff'
2023-05-01 13:22:22,659 - bsp_underwater_acoustic_comm.py:_read_bytes[line:201] - WARNING: WARNING : 水声通信设备(端口'COM5' 状态True) read frame length is not 57
2023-05-01 13:22:22,659 - bsp_underwater_acoustic_comm.py:_read_bytes[line:203] - WARNING: WARNING : 水声通信设备(端口'COM5' 状态True) read frmae without header b'U\xaa6'
2023-05-01 13:22:22,659 - bsp_underwater_acoustic_comm.py:_read_bytes[line:209] - WARNING: WARNING : 水声通信设备(端口'COM5' 状态True) read frmae without end b'\r\n'
2023-05-01 13:22:22,659 - bsp_underwater_acoustic_comm.py:read[line:149] - ERROR: 水声通信设备(端口'COM5' 状态True)读取文件发生错误, 错误原因： 未接收到正确的CMD_FILEINFO
2023-05-01 13:22:22,659 - core_scheduling.py:deal_data_forwarding_processhandle[line:108] - ERROR: ERROR   : 线程池处理DIRECT_DEVICE_TO_FILE任务124463
2023-05-01 13:22:22,661 - core_scheduling.py:deal_data_forwarding_callback[line:156] - CRITICAL: 线程池回调 ： 执行任务{task_id}失败
2023-05-01 13:22:39,864 - bsp_underwater_acoustic_comm.py:_read_bytes[line:198] - CRITICAL: 水声通信设备(端口'COM5' 状态True) 接收到一帧数据b'\xff'
2023-05-01 13:22:39,864 - bsp_underwater_acoustic_comm.py:_read_bytes[line:201] - WARNING: WARNING : 水声通信设备(端口'COM5' 状态True) read frame length is not 57
2023-05-01 13:22:39,864 - bsp_underwater_acoustic_comm.py:_read_bytes[line:203] - WARNING: WARNING : 水声通信设备(端口'COM5' 状态True) read frmae without header b'U\xaa6'
2023-05-01 13:22:39,865 - bsp_underwater_acoustic_comm.py:_read_bytes[line:209] - WARNING: WARNING : 水声通信设备(端口'COM5' 状态True) read frmae without end b'\r\n'
2023-05-01 13:22:39,865 - bsp_underwater_acoustic_comm.py:read[line:149] - ERROR: 水声通信设备(端口'COM5' 状态True)读取文件发生错误, 错误原因： 未接收到正确的CMD_FILEINFO
2023-05-01 13:22:39,865 - core_scheduling.py:deal_data_forwarding_processhandle[line:108] - ERROR: ERROR   : 线程池处理DIRECT_DEVICE_TO_FILE任务124464
2023-05-01 13:22:39,866 - core_scheduling.py:deal_data_forwarding_callback[line:156] - CRITICAL: 线程池回调 ： 执行任务{task_id}失败
