2023-04-30 16:34:31,080 - _internal.py:_log[line:113] - INFO:  * Running on http://localhost:1234/ (Press CTRL+C to quit)
2023-04-30 16:34:33,182 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:33] "[32mGET /device/data?perPage=10&page=1 HTTP/1.1[0m" 302 -
2023-04-30 16:34:33,195 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:33] "[37mGET /login/index HTTP/1.1[0m" 200 -
2023-04-30 16:34:34,174 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:34] "[32mGET /login/index?Username=root&Password=88888888 HTTP/1.1[0m" 302 -
2023-04-30 16:34:34,190 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:34] "[37mGET /device/index HTTP/1.1[0m" 200 -
2023-04-30 16:34:34,469 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:34] "[37mGET /device/data_operation?page=1&perPage=10 HTTP/1.1[0m" 200 -
2023-04-30 16:34:35,334 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:35] "[37mGET /device/data HTTP/1.1[0m" 200 -
2023-04-30 16:34:35,518 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:35] "[37mGET /device/data_operation?perPage=10&page=1 HTTP/1.1[0m" 200 -
2023-04-30 16:34:37,412 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:37] "[37mGET /device/file_operation/upload?page=1&perPage=10 HTTP/1.1[0m" 200 -
2023-04-30 16:34:39,336 - connection_workflow.py:start[line:179] - INFO: Pika version 1.3.1 connecting to ('::1', 5672, 0, 0)
2023-04-30 16:34:39,336 - io_services_utils.py:_on_writable[line:345] - INFO: Socket connected: <socket.socket fd=1324, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 14229, 0, 0), raddr=('::1', 5672, 0, 0)>
2023-04-30 16:34:39,337 - connection_workflow.py:_on_transport_establishment_done[line:428] - INFO: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000027610448A30>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000027610448A30> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2023-04-30 16:34:39,340 - connection_workflow.py:_report_completion_and_cleanup[line:293] - INFO: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000027610448A30> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 16:34:39,341 - connection_workflow.py:_report_completion_and_cleanup[line:725] - INFO: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000027610448A30> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 16:34:39,341 - blocking_connection.py:_create_connection[line:453] - INFO: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000027610448A30> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 16:34:39,341 - blocking_connection.py:__init__[line:1264] - INFO: Created channel=1
2023-04-30 16:34:39,342 - views.py:add_device_task_to_db[line:326] - ERROR: Task Error: Â∞ùËØïÂèëÂ∏É‰ªªÂä°ÔºàÊñá‰ª∂160 ËÆæÂ§á1)Âà∞ÊéßÂà∂ËΩØ‰ª∂Ôºå ÈîôËØØÂéüÂõ†unhashable type: 'slice'
2023-04-30 16:34:39,360 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:39] "[37mPOST /device/task_operation/1 HTTP/1.1[0m" 200 -
2023-04-30 16:34:39,369 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:34:39] "[37mGET /device/data_operation?perPage=10&page=1 HTTP/1.1[0m" 200 -
