2023-04-30 16:32:55,206 - _internal.py:_log[line:113] - INFO:  * Running on http://localhost:1234/ (Press CTRL+C to quit)
2023-04-30 16:32:57,085 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:32:57] "[32mGET /device/data?perPage=10&page=1 HTTP/1.1[0m" 302 -
2023-04-30 16:32:57,104 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:32:57] "[37mGET /login/index HTTP/1.1[0m" 200 -
2023-04-30 16:32:58,037 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:32:58] "[32mGET /login/index?Username=root&Password=88888888 HTTP/1.1[0m" 302 -
2023-04-30 16:32:58,058 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:32:58] "[37mGET /device/index HTTP/1.1[0m" 200 -
2023-04-30 16:32:58,316 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:32:58] "[37mGET /device/data_operation?page=1&perPage=10 HTTP/1.1[0m" 200 -
2023-04-30 16:32:59,477 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:32:59] "[37mGET /device/data HTTP/1.1[0m" 200 -
2023-04-30 16:32:59,670 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:32:59] "[37mGET /device/data_operation?perPage=10&page=1 HTTP/1.1[0m" 200 -
2023-04-30 16:33:01,730 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:33:01] "[37mGET /device/file_operation/upload?page=1&perPage=10 HTTP/1.1[0m" 200 -
2023-04-30 16:33:03,636 - connection_workflow.py:start[line:179] - INFO: Pika version 1.3.1 connecting to ('::1', 5672, 0, 0)
2023-04-30 16:33:03,637 - io_services_utils.py:_on_writable[line:345] - INFO: Socket connected: <socket.socket fd=1296, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 14082, 0, 0), raddr=('::1', 5672, 0, 0)>
2023-04-30 16:33:03,637 - connection_workflow.py:_on_transport_establishment_done[line:428] - INFO: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000029AE6C88A60>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000029AE6C88A60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2023-04-30 16:33:03,640 - connection_workflow.py:_report_completion_and_cleanup[line:293] - INFO: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000029AE6C88A60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 16:33:03,641 - connection_workflow.py:_report_completion_and_cleanup[line:725] - INFO: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000029AE6C88A60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 16:33:03,641 - blocking_connection.py:_create_connection[line:453] - INFO: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000029AE6C88A60> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 16:33:03,641 - blocking_connection.py:__init__[line:1264] - INFO: Created channel=1
2023-04-30 16:33:03,642 - views.py:add_device_task_to_db[line:322] - ERROR: Task Error: Â∞ùËØïÂèëÂ∏É‰ªªÂä°ÔºàÊñá‰ª∂160 ËÆæÂ§á1)Âà∞ÊéßÂà∂ËΩØ‰ª∂Ôºå ÈîôËØØÂéüÂõ†object of type 'mTask' has no len()
2023-04-30 16:33:03,658 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:33:03] "[37mPOST /device/task_operation/1 HTTP/1.1[0m" 200 -
2023-04-30 16:33:03,667 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:33:03] "[37mGET /device/data_operation?perPage=10&page=1 HTTP/1.1[0m" 200 -
