2023-04-30 16:27:54,469 - _internal.py:_log[line:113] - INFO:  * Running on http://localhost:1234/ (Press CTRL+C to quit)
2023-04-30 16:27:55,831 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:27:55] "[32mGET /device/data?perPage=10&page=1 HTTP/1.1[0m" 302 -
2023-04-30 16:27:55,844 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:27:55] "[37mGET /login/index HTTP/1.1[0m" 200 -
2023-04-30 16:27:56,493 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:27:56] "[32mGET /login/index?Username=root&Password=88888888 HTTP/1.1[0m" 302 -
2023-04-30 16:27:56,509 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:27:56] "[37mGET /device/index HTTP/1.1[0m" 200 -
2023-04-30 16:27:56,760 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:27:56] "[37mGET /device/data_operation?page=1&perPage=10 HTTP/1.1[0m" 200 -
2023-04-30 16:27:57,642 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:27:57] "[37mGET /device/data HTTP/1.1[0m" 200 -
2023-04-30 16:27:57,828 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:27:57] "[37mGET /device/data_operation?perPage=10&page=1 HTTP/1.1[0m" 200 -
2023-04-30 16:27:59,752 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:27:59] "[37mGET /device/file_operation/upload?page=1&perPage=10 HTTP/1.1[0m" 200 -
2023-04-30 16:28:01,672 - connection_workflow.py:start[line:179] - INFO: Pika version 1.3.1 connecting to ('::1', 5672, 0, 0)
2023-04-30 16:28:01,672 - io_services_utils.py:_on_writable[line:345] - INFO: Socket connected: <socket.socket fd=1144, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 13384, 0, 0), raddr=('::1', 5672, 0, 0)>
2023-04-30 16:28:01,673 - connection_workflow.py:_on_transport_establishment_done[line:428] - INFO: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001937D6B8A00>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001937D6B8A00> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2023-04-30 16:28:01,676 - connection_workflow.py:_report_completion_and_cleanup[line:293] - INFO: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001937D6B8A00> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 16:28:01,677 - connection_workflow.py:_report_completion_and_cleanup[line:725] - INFO: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001937D6B8A00> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 16:28:01,677 - blocking_connection.py:_create_connection[line:453] - INFO: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001937D6B8A00> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 16:28:01,677 - blocking_connection.py:__init__[line:1264] - INFO: Created channel=1
2023-04-30 16:28:01,678 - views.py:add_device_task_to_db[line:317] - ERROR: Task Error: Â∞ùËØïÂèëÂ∏É‰ªªÂä°ÔºàÊñá‰ª∂160 ËÆæÂ§á1)Âà∞ÊéßÂà∂ËΩØ‰ª∂Ôºå ÈîôËØØÂéüÂõ†object of type 'Tasks' has no len()
2023-04-30 16:28:01,694 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:28:01] "[37mPOST /device/task_operation/1 HTTP/1.1[0m" 200 -
2023-04-30 16:28:01,704 - _internal.py:_log[line:113] - INFO: 127.0.0.1 - - [30/Apr/2023 16:28:01] "[37mGET /device/data_operation?perPage=10&page=1 HTTP/1.1[0m" 200 -
